name: notify

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, closed, reopened]
  issues:
    types: [opened, closed, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: debug
        run: |
          echo "webhook_len=${{ secrets.DINGTALK_WEBHOOK == '' && 0 || secrets.DINGTALK_WEBHOOK.size() }}"
          echo "ref=${{ github.ref }}"
      - uses: yehuoshun/yehuoshun-notify@main
        with:
          webhook: ${{ secrets.DINGTALK_WEBHOOK }}